<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=divice-width, initial-scale=1, maximum-scale=1">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.css">
    <link rel="stylesheet" type="text/css" href="../../css/Estilo.css" media="screen and (min-width:641px)" />
    <link rel="stylesheet" type="text/css" href="../../css/Estilo-celular.css" media="screen and (max-width:640px)" />
    <link rel="shortcut icon" href="../../Imagens/Chibi_zeref.png" type="image/x-icon">
    <!-- Compiled and minified JavaScript -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.2.2.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.js"></script>
</head>